config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :schedule_name, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:schedule_name, :start_date, :end_date, :allday, :schedule_memo))
    if @schedule.save
      flash[:notice] = "新しく予定を登録しました"
      redirect_to :schedules
    else
      render :new
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:schedule_name, :start_date, :end_date, :allday, :schedule_memo))
      flash[:notice] = "予定を更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to schedules_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="schedule-header">
      <h1>スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer class="schedule-footer">
      <h1>残スケジュール数：<%= Schedule.count %></h2>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h3>スケジュール編集</h3>

<%= render "shared/error", obj: @schedule %>

<%= form_for @schedule do |f| %>
    <table>
        <tr>
            <th><%= f.label :schedule_name ,"スケジュール名" %></th>
            <td><%= f.text_field :schedule_name %></td>
        </tr>

        <tr>
            <th><%= f.label :start_date ,"開始日" %></th>
            <td><%= f.date_field :start_date %></td>
        </tr>

        <tr>
            <th><%= f.label :end_date ,"終了日" %></th>
            <td><%= f.date_field :end_date %></td>
        </tr>

        <tr>
            <th><%= f.label :allday ,"終日" %></th>
            <td><%= f.check_box :allday %></td>
        </tr>

        <tr>
            <th><%= f.label :schedule_memo ,"メモ" %></th>
            <td><%= f.text_area :schedule_memo %></td>
        </tr>
    </table>

    <div>
        <ul>
            <li><%= f.submit "作成完了"%></li>
            <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        </ul>
    </div>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧</h2>

<% if flash.notice %>
<p class="schedule-notice"><%= flash.notice %></p>
<% end %>

<table class="schedule-list">
    <thead>
        <tr>
            <th>ID</th>
            <th>スケジュール名</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>最終更新</th>
            <th>確認</th>
            <th>編集</th>
            <th>削除</th>
        </tr>
    </thead>
    
    <tbody>
        <% @schedules.each do |schedule| %>
            <tr>
                <td><%= schedule.id %></td>
                <td><%= schedule.schedule_name %></td>
                <td><%= l schedule.start_date %></td>
                <td><%= l schedule.end_date %></td>
                <!--終日の箇所の出力処理-->
                <% if schedule.allday %>
                <td>○</td>
                <% else %>
                <td></td>
                <% end %>
                <td><%= l schedule.updated_at %></td>
                <td><%= link_to "詳細確認", schedule_path(schedule.id) %></td>
                <td><%= link_to "編集", edit_schedule_path(schedule.id) %></td>
                <td><%= link_to "削除", schedule_path(schedule.id), method: :delete, data: {confirm: "この予定を削除してよろしいですか？"} %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<p><%= link_to "新規スケジュール作成", :new_schedule %></p>

app/views/schedules/new.html.erb
<h3>スケジュール新規作成</h3>

<%= render "shared/error", obj: @schedule %>

<%= form_for @schedule do |f| %>
    <table>
        <tr>
            <th><%= f.label :schedule_name ,"スケジュール名" %></th>
            <td><%= f.text_field :schedule_name %></td>
        </tr>

        <tr>
            <th><%= f.label :start_date ,"開始日" %></th>
            <td><%= f.date_field :start_date %></td>
        </tr>

        <tr>
            <th><%= f.label :end_date ,"終了日" %></th>
            <td><%= f.date_field :end_date %></td>
        </tr>

        <tr>
            <th><%= f.label :allday ,"終日" %></th>
            <td><%= f.check_box :allday %></td>
        </tr>

        <tr>
            <th><%= f.label :schedule_memo ,"メモ" %></th>
            <td><%= f.text_area :schedule_memo %></td>
        </tr>
    </table>

    <div>
        <ul>
            <li><%= f.submit "作成完了"%></li>
            <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        </ul>
    </div>
<% end %>

app/views/schedules/show.html.erb
<h3>スケジュール詳細</h3>

<table>
    <tr>
        <th>スケジュール名</th>
        <td><%= @schedule.schedule_name %></td>
    </tr>
    <tr>
        <th>開始日</th>
        <td><%= @schedule.start_date %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= @schedule.end_date %></td>
    </tr>
    <tr>
        <th>終日</th>
        <% if @schedule.allday %>
        <td>○</td>
        <% else %>
        <td></td>
        <% end %>
    </tr>
    <tr>
        <th>メモ</th>
        <td><%= @schedule.schedule_memo %></td>
    </tr>
</table>

<div>
    <ul>
    <li><%= link_to "ユーザー情報一覧に戻る", :schedules %></li>
    <li><%= link_to "この予定を編集する", edit_schedule_path(@schedule.id) %></li>
    <li><%= link_to "この予定を削除する", schedule_path(@schedule.id), method: :delete, data: {confirm: "本当に削除しますか？"} %></li>
    </ul>
</div>

app/views/shared/_error.html.erb
    <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li class="error-message"><%= message %></p>
        </ul>
      <% end %>
    <% end %>